name: lunar-magnetic-biology
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib=3.8.3
  - cartopy=0.22.0
  - scipy=1.12.0
  - requests=2.31.0
  - lxml=5.1.0
  - pyproj=3.6.1
  - shapely=2.0.3
  - pillow=10.2.0
  - pip:
    - cffconvert==2.0.0
